parameters:
    locale: de
    liqpay:
        sandbox: false
    sms:
        customerBooked: false
        customerRemind: false
        managerBooked: false
        managerRemind: false
    email:
        customerBooked: false
        customerFeedback: false
        customerCallback: false
        managerBooked: false
        managerFeedback: false
        managerCallback: false
    discount:
        discount: '5'
        reward: '5'
