parameters:
    locale: de
    liqpay:
        sandbox: true
    sms:
        customerBooked: false
        customerRemind: false
        managerBooked: false
        managerRemind: false
    email:
        customerBooked: true
        customerFeedback: true
        customerCallback: true
        managerBooked: true
        managerFeedback: true
        managerCallback: true
    discount:
        discount: '5'
        reward: '5'
