parameters:
    locale: de
    admin:
        email: mp091689@gmail.com
    liqpay:
        sandbox: true
    sms:
        customerBooked: true
        customerRemind: false
        managerBooked: true
        managerRemind: false
    email:
        customerBooked: true
        customerFeedback: true
        customerCallback: true
        customerReward: true
        managerBooked: true
        managerFeedback: true
        managerCallback: true
        managerReward: true
        managerPayment: true
    discount:
        discount: '5'
        reward: '5'
