admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /nepanikuy
    defaults: { _locale: en }

web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /