home_page_without_prefix:
    path:     /
    defaults: { _controller: WebBundle:Default:index, _locale: ru }

web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: ru }
    requirements:
        _locale: ru|en|de

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /nepanikuy
    defaults: { _locale: en }

fos_user_security:
    prefix: /nepanikuy
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    defaults: { _locale: en }