mykyta_admin:
    resource: "@MykytaAdminBundle/Controller/"
    type:     annotation
    prefix:   /adminpanic

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin