parameters:
    #parameter_name: value

services:
    image_uploader:
        class: AdminBundle\Service\ImageUploader

    mail_sender:
        class: AdminBundle\Service\MailSender
        arguments:
            - '@service_container'

    turbosms_sender:
        class: AdminBundle\Service\SmsSender
        arguments:
            - '%turbosms_host%'
            - '%turbosms_name%'
            - '%turbosms_user%'
            - '%turbosms_pass%'
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    uuid:
        class: AdminBundle\Service\Uuid

    payment:
        class: WebBundle\Service\Payment
        arguments:
            - '@service_container'
            - '@translator.default'
            - '@uuid'
            - '@router'

    room_voter:
        class: AdminBundle\Security\RoomVoter
        tags:
            - { name: security.voter }

    payment.logger:
        class: WebBundle\Service\PaymentLogger
        arguments:
            - '@logger'
        tags:
            - { name: monolog.logger, channel: 'payment_channel' }