# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    admin.file_uploader:
            class: AdminBundle\Service\FileUploader
            arguments: ['%uploads_rooms_path%']

    mail_sender:
            class: AdminBundle\Service\MailSender
            arguments: ['@mailer', '@templating']

    room_voter:
        class: AdminBundle\Security\RoomVoter
        tags:
            - { name: security.voter }