parameters:
    #parameter_name: value

services:
    image_uploader:
        class: AdminBundle\Service\ImageUploader

    mail_sender:
        class: AdminBundle\Service\MailSender
        arguments:
            - '@service_container'

    turbosms_sender:
        class: AdminBundle\Service\SmsSender
        arguments:
            - '@service_container'

    uuid:
        class: AdminBundle\Service\Uuid

    payment:
        class: WebBundle\Service\Payment
        arguments:
            - '@service_container'
            - '@translator.default'
            - '@uuid'
            - '@router'

    room_voter:
        class: AdminBundle\Security\RoomVoter
        tags:
            - { name: security.voter }

    debug.logger:
        class: AdminBundle\Service\DebugLogger
        arguments:
            - '@logger'
        tags:
            - { name: monolog.logger, channel: 'custom_debug_channel' }