# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    admin.file_uploader:
        class: AdminBundle\Service\FileUploader
        arguments: ['%uploads_rooms_path%']

    mail_sender:
        class: AdminBundle\Service\MailSender
        arguments: ['@mailer', '@templating', '@doctrine.orm.entity_manager']

    turbosms_sender:
        class: AdminBundle\Service\SmsSender
        arguments: ['%turbosms_host%', '%turbosms_name%', '%turbosms_user%', '%turbosms_pass%', '@doctrine.orm.entity_manager']

    uuid:
        class: AdminBundle\Service\Uuid

    payment:
        class: WebBundle\Service\Payment
        arguments: ['%liqpay_public_key%', '%liqpay_private_key%', '@translator.default']

    room_voter:
        class: AdminBundle\Security\RoomVoter
        tags:
            - { name: security.voter }